server:
  port: "8282"
  read_timeout: "120s"
  write_timeout: "120s"
  idle_timeout: "180s"
  request_timeout: "15m"

services:
  auth:
    base_url: "http://localhost:8081"
    timeout: "30s"
    retries: 3
  communication:
    base_url: "http://localhost:8082"
    timeout: "30s"
    retries: 3
  company:
    base_url: "http://localhost:8083"
    timeout: "30s"
    retries: 3
  user:
    base_url: "http://localhost:8085"
    timeout: "30s"
    retries: 3
  user_consents:
    base_url: "http://localhost:8086"
    timeout: "30s"
    retries: 3
  user_profile:
    base_url: "http://localhost:8091"
    timeout: "30s"
    retries: 3

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  vhost: "/"
  exchange: "ms-communication-exchange-local"
  #exchange: "ms-communication-exchange-dev"
  routing_key: "communication.message.send"
  durable: true
  auto_delete: false

jwt:
  secret: "Q2FjaG9ycm8gU2VndXJhbmNhIFByb2pldG8gS2VlcEd1YXJkIQ=="
  issuer: "keepguard"
  audience: "keepguard-api"

redis:
  host: ${REDIS_HOST:localhost}
  port: 6379
  password: ${REDIS_PASSWORD:}
  db: 0

rate_limit:
  enabled: true
  rules:
    register_init:
      limit: 100
      window: 60s
    register_resend:
      limit: 100
      window: 60s
    register_confirm:
      limit: 100
      window: 60s
    consents:
      limit: 500
      window: 60s
    default:
      limit: 500
      window: 60s

metrics:
  enabled: true
  scrape_path: "/metrics"
  port: "9090"

log:
  level: "debug"
  format: "json"


env: "local"
